### ISSUE TITLE
Support aliases to vim/nvim

### ISSUE THREAD

**Issue by jajaperson** [lambdalisue/guise.vim#13]
It's only one keystroke, but I have `vi` aliased to `nvim` and my muscle memory is to use that to edit files. Would it be possible to either override the behaviour of commands aliased to vim/nvim the same way, or to allow a custom list of commands to be overrided?

**Comment by lambdalisue** [comment]
I'm not sure, but I think it's not guise.vim's job to put aliases, but your shell's job.

**Comment by jajaperson** [comment]
No you misunderstand me, I'm saying that with the alias set by my shell, `vi` would not trigger guise's functionality but instead open a nested vim session.

**Comment by lambdalisue** [comment]
Well, I think you are misunderstanding the guise.vim. It does not care about the name. That's shell's business.

If `vi` is properly aliased to `vim` that load guise.vim properly in your shell, it won't start. That functionality is written in [`plugin/guise.vim`](https://github.com/lambdalisue/guise.vim/blob/main/plugin/guise.vim) without naming rules or so on.
