### ISSUE TITLE
Don't wait for the buffer to close

### ISSUE THREAD

**Issue by sigmaSd** [lambdalisue/guise.vim#20]
By removing the `await` here https://github.com/lambdalisue/guise.vim/blob/main/denops/guise/editor.ts#L52

some context https://github.com/lambdalisue/guise.vim/issues/19

https://user-images.githubusercontent.com/22427111/169171483-d620c56f-bd61-4020-9f00-36d20fd200bf.mov

You can see the only problem that remains is if I switch buffers then try to return it tells me that the buffer does not exist, I'm still tryingto figure that one out.

**Comment by lambdalisue** [comment]
Well... I'm not sure I understand the context properly but we need to wait at there. Otherwise, for example, `git commit` or command that relies on `$EDITOR` does not work properly I guess.

**Comment by sigmaSd** [comment]
Hmm maybe it's a nich usecase, thanks for your time
